<h1>Logistic Regression</h1>

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('daibetes.xlsx')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [7]:
X = df.drop('Outcome', axis = 1)
y= df['Outcome'].values
print(df.shape, X.shape, y.shape)

(768, 9) (768, 8) (768,)


In [27]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.2 , random_state = 32)

In [28]:
model = LogisticRegression(max_iter=1000)

In [29]:
model.fit(X_train ,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [30]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0])

In [31]:
matrix = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(matrix)
print(acc)
print(report)

[[85 14]
 [19 36]]
0.7857142857142857
              precision    recall  f1-score   support

           0       0.82      0.86      0.84        99
           1       0.72      0.65      0.69        55

    accuracy                           0.79       154
   macro avg       0.77      0.76      0.76       154
weighted avg       0.78      0.79      0.78       154



In [32]:
matrix

array([[85, 14],
       [19, 36]])

In [33]:
acc

0.7857142857142857

In [34]:
print(report)

              precision    recall  f1-score   support

           0       0.82      0.86      0.84        99
           1       0.72      0.65      0.69        55

    accuracy                           0.79       154
   macro avg       0.77      0.76      0.76       154
weighted avg       0.78      0.79      0.78       154



## Building linear regression on diabetes data

In [35]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [36]:
y_pred_linreg = linreg.predict(X_test)
y_pred_linreg

array([ 4.97524626e-01,  2.94524383e-01,  4.55137485e-01,  1.27919839e-01,
        4.17955415e-01,  6.74009015e-02,  4.28862582e-01,  6.17693158e-01,
        7.51522398e-01,  2.68257159e-02,  3.03832966e-01,  3.27247929e-02,
        8.42556526e-02, -2.04749362e-01,  8.85083952e-02,  1.18965073e-01,
        4.57467081e-01,  7.17256648e-02,  5.54865952e-01,  3.56345449e-01,
        3.49745594e-01,  4.05730366e-01,  2.94497165e-01,  5.63863344e-01,
        2.98346788e-01,  1.24201070e-01,  8.35507479e-01,  6.43794435e-02,
        1.01827747e-01,  1.59511632e-01,  5.37425665e-01,  5.42820030e-01,
        3.24766561e-01,  3.80228208e-01,  5.21640436e-01,  2.70200939e-01,
        7.12794817e-01, -1.67988050e-01,  2.62807344e-01,  6.98918773e-01,
        7.51231563e-01,  5.58383853e-01,  5.93229615e-01,  4.25424467e-01,
        2.31509691e-01,  2.19453661e-01,  9.82605313e-01,  4.29780420e-01,
        6.59642400e-01,  3.91555946e-01,  4.75274519e-01,  5.27420453e-01,
        1.06463160e-01, -

In [37]:
print(y_pred_linreg.max())
print(y_pred_linreg.min())

1.0280771634073664
-0.2924254119054527


In [38]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error,r2_score
print( mean_squared_error(y_test, y_pred_linreg))
print(mean_absolute_error(y_test, y_pred_linreg))
print( root_mean_squared_error(y_test, y_pred_linreg))
print( r2_score(y_test, y_pred_linreg))

0.1421771836910383
0.31778501025119804
0.3770638986843454
0.3807393777012553


In [39]:
pred_list = y_pred_linreg.tolist()
print(pred_list)

[0.49752462624638905, 0.2945243827765436, 0.45513748496477646, 0.12791983867355494, 0.41795541510469914, 0.0674009015401289, 0.42886258214379414, 0.6176931584332961, 0.7515223977493781, 0.026825715911598547, 0.3038329659666503, 0.03272479285210994, 0.08425565264399026, -0.20474936240429342, 0.08850839524397514, 0.118965073204227, 0.45746708087417765, 0.0717256647882909, 0.5548659520249994, 0.35634544920454414, 0.34974559408313355, 0.4057303662325984, 0.29449716450295416, 0.5638633443726928, 0.29834678830547, 0.12420107035442851, 0.8355074786495893, 0.0643794434815751, 0.10182774693298813, 0.159511632496665, 0.5374256653716885, 0.5428200296464543, 0.32476656132089055, 0.3802282081088777, 0.5216404355179409, 0.2702009393172464, 0.7127948168926317, -0.16798805015395035, 0.2628073442075971, 0.6989187733960032, 0.7512315633467515, 0.5583838529649381, 0.5932296149314269, 0.42542446749506024, 0.23150969102789465, 0.21945366077209982, 0.9826053129715908, 0.42978042049567633, 0.6596424000691881

In [40]:
def sig(x):
    result= 1/(1 + np.exp(-x))
    return result

In [41]:
data_for_threshold = []
for i in pred_list:
    data_for_threshold.append(sig(i))

In [42]:
print(data_for_threshold)

[np.float64(0.6218774330855028), np.float64(0.5731034141722237), np.float64(0.6118600204418355), np.float64(0.5319364222764833), np.float64(0.6029938952895643), np.float64(0.516843849233489), np.float64(0.6056020308682198), np.float64(0.6496937118355284), np.float64(0.6795103314963664), np.float64(0.50670602683401), np.float64(0.5753792487707846), np.float64(0.5081804681792167), np.float64(0.5210514609144963), np.float64(0.44899073715330445), np.float64(0.5221126652967919), np.float64(0.5297062412970084), np.float64(0.6124131255848492), np.float64(0.5179237326962496), np.float64(0.6352637904732858), np.float64(0.5881554833849013), np.float64(0.586555884786051), np.float64(0.6000636602608508), np.float64(0.5730967550480021), np.float64(0.6373459715280128), np.float64(0.5740383258205272), np.float64(0.5310104141895164), np.float64(0.6975181963027057), np.float64(0.5160893041255813), np.float64(0.5254349628359682), np.float64(0.5397935683834449), np.float64(0.6312133589433546), np.float64

In [43]:
threshold = np.array(data_for_threshold).mean()
print(threshold)

0.5889084034855399


In [44]:
output = [1 if x > threshold else 0 for x in data_for_threshold]
print(output)

[1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1]


In [45]:
report_manual = classification_report(y_test, output)
print(report_manual)

              precision    recall  f1-score   support

           0       0.90      0.73      0.80        99
           1       0.64      0.85      0.73        55

    accuracy                           0.77       154
   macro avg       0.77      0.79      0.77       154
weighted avg       0.81      0.77      0.78       154

